export enum ExecutorState {
  IDLE = 'IDLE',
  VALIDATING = 'VALIDATING',
  CONFIRM = 'CONFIRM',
  BACKUP = 'BACKUP',
  QUEUE = 'QUEUE',
  LOCK = 'LOCK',
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  ROLLBACK = 'ROLLBACK',
  AUTO_RESCAN = 'AUTO_RESCAN',
  RECOMMENDATION = 'RECOMMENDATION',
  UNLOCK = 'UNLOCK',
  COMPLETE = 'COMPLETE'
}