export enum ExecutionEventType {
  STATE_CHANGED = 'STATE_CHANGED',
  PROGRESS_UPDATED = 'PROGRESS_UPDATED',
  LOG_EMITTED = 'LOG_EMITTED',
  ERROR_THROWN = 'ERROR_THROWN',
  COMPLETED = 'COMPLETED'
}