/**
 * Defines the levels for audit logging.
 */
export enum AuditLogLevel {
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL'
}

/**
 * Represents a single tamper-proof log entry for critical actions.
 */
export interface AuditLogEntry {
  id: string;                      // Unique ID of the log entry
  timestamp: number;               // When the event occurred
  level: AuditLogLevel;            // Severity level
  source: string;                  // Component that generated the log
  actionId?: string;               // Related Action ID (if applicable)
  sessionId?: string;              // Related Session ID
  message: string;                 // Human-readable message
  details?: Record<string, any>;   // Additional structured context
}

/**
 * Interface for Audit Logging system.
 * Audit logs are intended to be persistent and tamper-resistant.
 */
export interface AuditLogger {
  /**
   * Logs a new audit event.
   * @param entry Data for the log entry without id and timestamp (generated by the logger).
   */
  log(entry: Omit<AuditLogEntry, 'id' | 'timestamp'>): Promise<void>;

  /**
   * Retrieves all audit logs.
   * @returns Array of audit log entries.
   */
  getLogs(): Promise<AuditLogEntry[]>;
}
